### ISSUE TITLE
GSA/TTS - Regulations.gov Modernization Discovery - 8-10 weeks

### ISSUE THREAD

**Issue by thebestsophist** [GSA/tts-staffing#3]
### Project Description
eRulemaking is a new inclusion to the TTS suite of tools and includes two parts:
1. Regulations.gov is a public-facing site to find, review and comment on proposed regulations and the Federal.
2. The Federal Docket Management System (FDMS) is the agency-facing tool used to manage documents for public comments.
Related is ROCIS, which is used to submit PRA clearance requests, which is currently owned by OIRA. There may be good reasons to also explore making ROCIS and other regulations management-related systems interoperable with eRulemaking.
Regulations.gov is currently managed and maintained by a contractor and their current contract ends in September 2022 after which, the management and maintenance will be taken in-house to TTS. This will be an initial discovery project which will guide future teams to product development and delivery.
## Problem statement
A clear, trusted, and open policy making process is core to a well-functioning democracy. With the current contracts coming up to be recompeted (the Region 10 contracting office wants to get a solicitation out by April 19 for an award in September 2022), there is an opportunity to modernize Regulations.gov, the eRulemaking platform that runs it, and ROCIS in a way that makes policy documents more accessible and machine-readable, the rulemaking process more accessible, and improves how the public engages with and contributes to the policies that regulate their communities.
The current contractors have been running the systems for eRulemaking and ROCIS for over a decade and there haven’t been performance issues with the vendor. However, many of the systems involved are proprietary and new international standards and practices in policy technology means that a modernization effort provides a huge opportunity to build and move to a new system that makes the policy making process more open and transparent.

During discovery, the team will: 
- Make a recommendation on the future of the site: Should we ‘build’ a new regulations.gov or develop a contracting plan for a non- TTS team to support development?
- Start exploring (and building experiments) to pull data out of the current system. “How hard is it going to be to migrate all the data and structure it into a standard, machine-readable format that is interoperable with other regulatory data?”
- Exploring how to make policy documents accessible and machine readable
- Start exploring and mapping out the rulemaking journey. “How does the rulemaking process work and what challenges do users face?”
- Create a staffing request and define the corresponding skills needed to accomplish post-discovery work, including iterative development.
- What does ‘done’ look like? What outcomes and outputs would signal that the modernization is complete?
- Start exploring how ROCIS should interact with the eRulemaking system and whether they ought to be merged.

This is an initial discovery phase where the teams will work along two workstreams: 
**Technical workstream:**
- Understand and analyze the technical landscape for regulations.gov (including infrastructure analysis) 
- Develop a technical strategy to build, ship and maintain a new scalable and resilient regulations.gov
- Data migration decisions around pulling data out of the legacy system and into a new system and semantic markup
- Evaluate current TTS tools that can support a future roadmap

**Service design workstream:**
- Systems mapping across all of erulemaking (including regulations.gov)
- What are the core functionalities we need in place when the contract ends (multiple contracts for ROCIS and eRulemaking)?
- Product+service+policy roadmapping

Assessing and making recommendations for:
- 508 compliance (as defined by WCAG 2.1 AA guidelines)
- Plain Language 
- Multi language support 
- Domain expertise is absolutely valuable, but rare. Please let your staffing rep know if you have some. 
- Documents and materials
- TTS eRulemaking documents
- Pre-award (incoming)

**Potential complications**
- The current contract needs to be recompeted by September 2022. There are options to extend the current operations and maintenance (O&M) contracts for ROCIS and eRulemaking by 6 months, but a long-term strategy is needed.
- While eRulemaking and its team are joining TTS, ROCIS is still owned by OIRA so a long-term decision needs to be made.
- Congress is likely to pass $8.5 million for modernizing eRulemaking and ROCIS in the upcoming budget.

This work will lead into permanent work on an internal TTS-owned product but those long-term staffing considerations will happen later and members of this discovery team are only committed to the discovery project.

Direct questions about this engagement to Cordelia.

### Timeline
Required:
Duration of engagement: 8-10 weeks + the discovery team will need to create a long term staffing request and determine the scope and length of the ‘build’ project 
Start date: [insert project start date if other than “ASAP”]

### Skill type(s) needed
- [X] [Account Manager]  - Kristina Britt
 Number of weeks this role is needed: 8-10 weeks
 Hourly commitment per week: variable
- [x] [Acquisitions Lead]  Brittany Chappell
 Number of weeks this role is needed: 8-10 weeks
 Hourly commitment per week: variable
Product/stakeholder management discovery workstream
- [X] Product -- Kevin Mori
  Scrum master
  Extremely clear communicator
  Product roadmapping and prioritization
  Making trade off decisions
  Number of weeks this role is needed: 8-10 weeks
  Hourly commitment per week: 100%
- [x] Project lead @thebestsophist 
  Stakeholder management 
  Consulting and partner relationship-building
  Stakeholder interviewing and synthesis
  Extremely clear communicator 
  Facilitation a plus
  Be able to understand the policy and regulatory space
  Number of weeks this role is needed: 8-10 weeks
  Hourly commitment per week: 100%

#### Tactical discovery workstream:
- [X] Consulting Engineer 1 of 2 - Kimball Bighorse
- [X] Consulting Engineer 2 of 2 - Ron Williams
 
Tech assessment of the current systems
System to collect / centralize / normalize data and present it
Be able to map a path forward and provide very rough estimates on effort levels for various features and improvements 
Additional possible needs: finding project analogies, shaping procurement
Participation in user research
Testing migration path for data
Number of weeks this role is needed: 8-10 Weeks
Hourly commitment per week: 100%

- [X] Service design/design -- Ryan Wold
- [X] Service design/design -- Em Herrick
Map the federal policy rulemaking process 
Assess the eRulemaking and ROCIS systems from a user experience standpoint 
Ideally, this person would be comfortable leading research and developing lo-fidelity prototypes for testing during the prototyping phase.
Number of weeks this role is needed: 8-10 Weeks
Hourly commitment per week: 100%

#### On Call SME’s:
On Call SME’s is expected to be minimal overhead along the duration of the project. The project lead (and the team) will engage SME’s for the scope and duration of the work.  
~- [ ] Multi language support
Support the project team as needed in understanding, assessing and making recommendations for future product development teams to implement
 Number of weeks this role is needed: Variable
 Hourly commitment per week: Variable~ -- per Cordelia this role is not needed at this time (1/27/22)

- [X] 508 Compliance support - Toni Bonitto
Support the project team as needed in understanding, assessing and making recommendations for future product development teams to implement
 Number of weeks this role is needed: Variable
 Hourly commitment per week: Variable

- [x]  Plain language content support — @amandacostello
Support the project team as needed in understanding, assessing and making recommendations for future product development teams to implement
 Number of weeks this role is needed: Variable
 Hourly commitment per week: Variable

**Prior to closing this issue**
- [ ] Ping @ that the issue is ready to close, so they can update some things.

**Comment by abrouilette** [comment]
Okay!   Per a conversation with Ashley Mahan, for this issue 18F Staffing needs to provide: 
*one of the two consulting engineers
*the Service Designer
*_Either_ a PM or an AM

**Comment by fedrampashley** [comment]
Confirmed Account Manager, 50% of a Service Design & Delivery team member (will have more info on 1/24 if we are able to increase availability), and 508/plain language support (only needed on ad-hoc basis). Awaiting confirmation from @adam-grandt-tts for one of two engineering roles.

**Comment by fedrampashley** [comment]
Confirmed engineering role with @adam-grandt-tts. Identified potential PM, will confirm 1/25.

**Comment by SelenaJV** [comment]
18F can staff Kevin Mori to serve as PM on this project. He'll be available in the next week or so. @abrouilette can you write this into the issue since I don't have access yet? Thanks!

**Comment by alexbielen** [comment]
18F engineering can staff Kimball Bighorse to one of the consulting software engineering roles. Should be available immediately.

**Comment by abrouilette** [comment]
@fedrampashley, @adam-grandt-tts, who ya got? :)

**Comment by fedrampashley** [comment]
Account Manager - Kristina Britt (Solutions), Engineer - Ron Williams (COE), Service Design (Ryan Wold), 508 Compliance Consulting Support - Toni Bonitto (Solutions),

**Comment by abrouilette** [comment]
Thank you!

**Comment by abrouilette** [comment]
@thebestsophist, you are (mostly) good to go.  

If there is a second service designer available, we will know tomorrow (per Trammell) 

No readily apparent help available for multi-language support.

**Comment by abrouilette** [comment]
Adjusted request to reflect comms from @thebestsophist that multilanguage support is unnecessary at this time.

**Comment by tram** [comment]
The 18F Design chapter is pleased to staff @em-herrick in the service designer role.

**Comment by abrouilette** [comment]
Thank you!  @thebestsophist, you are clear for takeoff.
